GET /users HTTP/1.1
Host: localhost:8989

###
GET /users/2 HTTP/1.1
Host: localhost:8989

### user1
POST /users HTTP/1.1
Host: localhost:8989
Content-Type: application/json

{
    "name": "Admin 1",
    "email": "admin@mail.com",
    "password": "admin123"
}
### user2
POST /users HTTP/1.1
Host: localhost:8989
Content-Type: application/json

{
    "name": "Admin 2",
    "email": "admin2@mail.com",
    "password": "admin123"
}

###
DELETE /users/2 HTTP/1.1
Host: localhost:8989

###
PATCH /users/1 HTTP/1.1
Host: localhost:8989

{
    "password": "12345678"
}

###
POST /register HTTP/1.1
Host: localhost:8989
Content-Type: application/json

{
    "name": "admin 1",
    "email": "admin@mail.com",
    "password": "admin1234"
}

###
POST /login HTTP/1.1
Host: localhost:8989
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin1234"
}

###
GET /product HTTP/1.1
Host: localhost:8989
Content-Type: application/json

###
GET /product/1 HTTP/1.1
Host: localhost:8989
Content-Type: application/json

###
POST /product HTTP/1.1
Host: localhost:8989
Content-Type: application/json

{
    "product_name": "Americano",
    "product_tag": "Delicious strong black coffee",
    "price": 15000,
    "category": "coffee" 
}